### ISSUE TITLE
Packet Decoration not honoring data alignment.

### ISSUE THREAD

**Issue by bstastnyleapmotion** [leapmotion/autowiring#1042]
It is a known bug that make_shared does not honor data alignment requirements.  

converting this type of code: 
 auto ptr = std::make_shared<TActual>(std::forward<T&&>(t));

To:
auto ptr = std::shared_ptr<TActual>(new TActual(std::forward<T&&>(t)));

Will fix the issue(s)

**Comment by jdonald** [comment]
This was fixed in #1043
