### ISSUE TITLE
Autowiring failed when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [leapmotion/autowiring#1059]
Hi all,

For the issue https://github.com/leapmotion/autowiring/issues/1057 I reported before. This issue seems not to be solved completely. For the code in filesystem.h:
```
#if !defined(_MSC_VER) || _MSC_VER < 1914 || _MSVC_LANG < 201402L
```
This is also need to change as 201403L. We are no longer hit this issue when we changed to 201403L. Could you please help take a look at this? Thanks a lot!

Thanks 
Shanshan

**Comment by jdonald** [comment]
Sorry about that. Please try out #1060 and confirm. I should have been more careful the first time and this wouldn't have taken three separate pull requests!
