### ISSUE TITLE
Provide TLS security support for AutoNetServer

### ISSUE THREAD

**Issue by jnguyen75** [leapmotion/autowiring#390]
As we are using AutoNetServer as the RPC messaging, we should look into adding TLS support so that AutoNetServer can communicate with web applications with a more secure protocol

**Comment by pehrlich** [comment]
(Especially as some of our internal tooling demands https for proper security)

**Comment by gtremper** [comment]
The transport layer has been separated from AutoNet, so an external secure websocket server can be used.

**Comment by codemercenary** [comment]
Going to call this one "closed," in that case.
