### ISSUE TITLE
cmake find_package autowiring_DIR is misleading

### ISSUE THREAD

**Issue by vdods** [leapmotion/autowiring#525]
Pointing autowiring_DIR at the root dir (e.g. /path/to/autowiring-0.5.4) doesn't satisfy find_package.  Pointing autowiring_DIR at the cmake subdir does work, but I wouldn't consider this to be "the autowiring dir", so it's somewhat misleading.

Recommend putting the relevant cmake files (autowiring-config.cmake and autowiring-configVersion.cmake) in the autowiring root dir.

**Comment by codemercenary** [comment]
I don't think we can move them there for technical reasons.

@gtremper, thoughts?

**Comment by jdonald** [comment]
+1 because I tripped on this the other day. Took a while to figure out why it wouldn't accept my alternate autowiring build dir when I edited my CMake variables.

Other libraries don't suffer from this problem, so it ought to be possible to fix.

**Comment by gtremper** [comment]
autowiring_DIR is created by cmake and needs to point to the autowiring cmake config files. In autowiring installs, they are put in a "cmake" directory. I think that's cause the automatic cmake package search looks for a directory with that name. But maybe the cmake config files can be moved to the root project directory?

**Comment by codemercenary** [comment]
A wild @gtremper appears

**Comment by codemercenary** [comment]
Might be best to move this stuff to the root directory--though it does depend on what's standard.  How do most modules solve this problem?  Do they usually have cmake finder stuff in the root or in a subdirectory?

**Comment by codemercenary** [comment]
Also, is it the `find_package` command that has this behavior, or something else?

**Comment by jdonald** [comment]
I just noticed my Qt5_DIR is set to G:/Libraries-x64_vc12/qt-5.2.0/lib/cmake/Qt5 so Qt suffers from the same problem.

But OpenCV_DIR (from back when we used OpenCV) gets set as the OpenCV root, and OpenCVConfig.cmake.in is in there.

**Comment by veronicaz41** [comment]
As @gtremper pointed out, `find_package` searches for cmake config files (autowiring-config.cmake and autowiring-configVersion.cmake), and then create a cache entry called `autowiring_DIR` to hold the directory containing the config files.
(https://cmake.org/cmake/help/v3.0/command/find_package.html Config mode)

If we want `autowiring_DIR` to point to autowiring root directory, the config files need to be installed in the root directory.

Not sure what is the standard though. Apart from what @jdonald mentioned, for libraries we are using, `components` has the config files in its root dir. `qt`, `libuvc`, `assimp` has the config files in `iib/cmake/<library_name>`.

It makes sense to me to move the config files to the root dir though. `LeapSerial` has the same problem as well.
