### ISSUE TITLE
Cyclical dependency analysis tool needed

### ISSUE THREAD

**Issue by wal-rus** [leapmotion/autowiring#671]
If class A autowires class B, and class B autowires class A, the resulting cyclical dependency will keep them both alive even after context teardown.
This is bad behavior, and if at all possible, we should add some mechanism for automatically detecting this kind of thing to either autowiring itself (which should throw an exception, likely runtime if found) or to AutoNet

**Comment by codemercenary** [comment]
This feature might be obviated by c136bca.  Context unlinking actually works _very_ effectively, if we use it everywhere (or even better, make the behavior canonical) we may never have this problem again.

Thoughts, @wal-rus?

**Comment by wal-rus** [comment]
If we made it the canonical behavior, sure

**Comment by codemercenary** [comment]
In that case, I propose we close this ticket as addressed by #697.

**Comment by wal-rus** [comment]
Agreed.
