### ISSUE TITLE
Fix debugging through an autosignal hanging VS2013/15

### ISSUE THREAD

**Issue by wal-rus** [leapmotion/autowiring#682]
If you try and set a breakpoint in a function with a couple of autosignals on the callstack, it hangs visual studio.  Admitedly, this is a problem with Visual Studio, but in practice it means that debugging code that uses autosignals on windows is extremely cumbersome.

**Comment by codemercenary** [comment]
We should probably look into this more.  It's likely a problem with the complexity of the variables involved--simplification of the call tree might be all it takes to fix this bug.

**Comment by codemercenary** [comment]
@wal-rus do you think you could create a branch that has some code which creates the hang?  Then I have something to tinker with.

**Comment by codemercenary** [comment]
Looks like this is actually fixed by correcting an unrelated issue in Platform having to do with `WH_KEYBOARD_LL`.  Closing.
