### ISSUE TITLE
ContextMap does not have a Clear() method

### ISSUE THREAD

**Issue by jnguyen75** [leapmotion/autowiring#719]
In cases where we manage our contexts using the ```ContextMap```, it would be nice if we could terminate and release the weak pointers in the map.  For example:

```C++
void MyClass::Reset() {
    for (auto ctxt : m_ctxtMap) {
        ctxt->SignalShutdown();
    }
    m_ctxtMap.Clear();
}
```

**Comment by codemercenary** [comment]
Implemented, but I chose the lower-case `clear` method name instead to have better parity with STL signatures.
