### ISSUE TITLE
NotifyWhenAutowired appears to be satisfied out of order

### ISSUE THREAD

**Issue by jhe-** [leapmotion/autowiring#738]
Example use case is with sliders, which use `NotifyWhenAutowired` on Figure. When I start LeapSvc with a device plugged in, a couple frames will tend to get processed before Figure comes online.

However, once Figure is autowired, these are often triggered in a different order than the `m_Params.NotifyWhenAutowired` line was called, which knocks sliders from their intended ordering.

This doesn't happen when I plug in a device after a few seconds, since at that point the calls to add sliders are processed immediately.

**Comment by codemercenary** [comment]
Ok we've got a unit test on this one, we'll fix this for the next release.
