### ISSUE TITLE
Service crash occurs after sleep/resume

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/autowiring#762]
#### Description: 
A service crash occurs after sleep/resume. This did not occur on Develop prior to autowiring update. Stack trace and branch commit hash attached below.
#### Frequency: 
10/10
#### Found In: 
UPD-Autowiring branch: a0c90e87cc9e174272aa3f1150d90810f8c9e97a
#### Notes: 
Stack Trace:
>	msvcr120.dll!abort() Line 88	C
 	msvcr120.dll!_purecall() Line 59	C
 	LeapSvc.exe!autowiring::signal<void >::operator()<enum VigilanceReason>(enum VigilanceReason &&)	C++
 	LeapSvc.exe!operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,enum LEDMode)	C++
 	LeapSvc.exe!DispatchQueue::DispatchAllEvents(void)	C++
 	LeapSvc.exe!CoreJob::DispatchAllAndClearCurrent(void)	C++
 	LeapSvc.exe!std::_Func_impl<struct std::_Callable_obj<class std::_Bind<0,void,class <lambda_21250f153e69945bed5dd5697e2e3945> >,0>,class std::allocator<class std::_Func_class<void> >,void>::_Do_call(void)	C++
 	LeapSvc.exe!std::_Packaged_state<void >::_Call_immediate(void)	C++
 	LeapSvc.exe!std::_Func_impl<struct std::_Callable_obj<class <lambda_2cb696077b3339a1ae8328ae0c6c0dec>,0>,class std::allocator<class std::_Func_class<void> >,void>::_Do_call(void)	C++
 	LeapSvc.exe!std::_Func_impl<struct std::_Callable_obj<class <lambda_76f314ecb5e1c9167539137e0dc2f350>,0>,class std::allocator<class std::_Func_class<unsigned char> >,unsigned char>::_Do_call(void)	C++
 	LeapSvc.exe!Concurrency::task<unsigned char>::_InitialTaskHandle<void,class <lambda_781036f848fffa6eb15265e2650f848e>,struct Concurrency::details::_TypeSelectorNoAsync>::_Init(struct Concurrency::details::_TypeSelectorNoAsync)	C++
 	LeapSvc.exe!Concurrency::details::_PPLTaskHandle<unsigned char,struct Concurrency::task<unsigned char>::_InitialTaskHandle<void,class <lambda_781036f848fffa6eb15265e2650f848e>,struct Concurrency::details::_TypeSelectorNoAsync>,struct Concurrency::details::_TaskProcHandle>::invoke(void)	C++
 	msvcr120.dll!Concurrency::details::_UnrealizedChore::_UnstructuredChoreWrapper(Concurrency::details::_UnrealizedChore * pChore) Line 293	C++
 	msvcr120.dll!Concurrency::details::InternalContextBase::Dispatch(Concurrency::DispatchState * pDispatchState) Line 1716	C++
 	msvcr120.dll!Concurrency::details::FreeThreadProxy::Dispatch() Line 203	C++
 	msvcr120.dll!Concurrency::details::ThreadProxy::ThreadProxyMain(void * lpParameter) Line 174	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
>

#### ENG Requirements:

**Comment by codemercenary** [comment]
We should be able to address this with the next Autowiring release.
