### ISSUE TITLE
Adding an AutoFilter lambda to a packet while being processing results in being called twice

### ISSUE THREAD

**Issue by veronicaz41** [leapmotion/autowiring#829]
There appears to be a race condition in Autowiring where adding an AutoFilter
lambda to a packet while it is processing may result in it being called twice.

This problem happens in Platform (See PR #4044).

**Comment by codemercenary** [comment]
I believe this may be a duplicate of #704.

**Comment by codemercenary** [comment]
This issue should be addressed already, I don't see it reported anymore.

**Comment by codemercenary** [comment]
I think #866 may have addressed this one.

**Comment by codemercenary** [comment]
Closing as duplicate.
