### ISSUE TITLE
More verbosity with "Attempted to dereference a null autowired field"

### ISSUE THREAD

**Issue by jhe-** [leapmotion/autowiring#835]
I get this error frequently, but the message is very unhelpful. Surely with RTTI we can at least print out a string representation of the offending type?

**Comment by jnguyen75** [comment]
:+1: I am sure there should at least be a way to communicate the type?

**Comment by jdonald** [comment]
This would be a nice to have feature, but I don't really blame autowiring for lacking it.

I mean, even without autowiring if you do `nullptr->Func()` you get a segfault (i.e. the error message is unhelpful) and may have to resort to running in gdb or the Visual Studio debugger to get your stack trace and find where your `obj->Func()` should be something like `obj && obj->Func()`. But that's what we get for dereferencing a null object.

**Comment by jnguyen75** [comment]
@jdonald definitely agree, I just hope that since the autowiring syntax includes a ```template<T>``` parameter, it would help if the exception message could classify what that template type is.

**Comment by jhe-** [comment]
Yes, null objects should not be dereferenced. But typically they come as a result of some high level code reshuffling. The specific example I ran into today only happens on Mac and Linux so I don't have a local machine where I can debug it.

It could, for instance, be caused by something as subtle as calling Autowired when I'm in the wrong context, which leads me to assume that the object exists.

**Comment by codemercenary** [comment]
Have a look at the above PR, let me know if this is what you want.
