### ISSUE TITLE
Double-decoration error in Autowiring v1.0.0

### ISSUE THREAD

**Issue by codemercenary** [leapmotion/autowiring#920]
There's a defect introduced in #866 which is causing a multi-decorate problem to appear on initialization in certain user build cases.  This defect is serious enough to merit a patch release this week to correct the problem.

The issue is only reproduceable in platform.  This is a copy of the error log:

```
[Critical] Unhandled exception: Cannot decorate this packet with type SubFrame, the requested decoration is already satisfied
[Critical] An unhandled exception occurred in a device context: Cannot decorate this packet with type SubFrame, the requested decoration is already satisfied
```

**Comment by veronicaz41** [comment]
This is related to this PR: https://github.com/leapmotion/autowiring/pull/866
And in platform, the exception throw at "ImageDebug"
