### ISSUE TITLE
Fix AutoNet

### ISSUE THREAD

**Issue by codemercenary** [leapmotion/autowiring#922]
AutoNet seems to be having some pretty serious problems as of v1.0.0.  In particular, not all of the context information is correctly relayed to the front end, and it does not update continuously.

One possible problem is the recent update to websocketpp, another possibility is a change to how Autowiring reports context events to clients.  Investigate, and fix the problem.

**Comment by gittyupagain** [comment]
There is still an issue with the AutoNet visualizer. Although it now shows the contexts and context members, the Context graph is not properly updated when contexts are added or removed.

**Comment by codemercenary** [comment]
Did you refresh your AutoNet page since the last time this was tested?  I had to do that to clear out some invalid state.

**Comment by gittyupagain** [comment]
Yes.
