### ISSUE TITLE
Autowiring directory uppercased in Linux package

### ISSUE THREAD

**Issue by raimo** [leapmotion/autowiring#987]
The Linux package contains Autowiring-1.0.3-Linux, not autowiring-1.0.3-Linux as expected.

Connected to leapmotion/PipelineAutomation#864

**Comment by codemercenary** [comment]
I'll rename the package contents and close this.

**Comment by codemercenary** [comment]
Should be fixed, can you confirm?

**Comment by geminatea** [comment]
It's fixed!
